### ISSUE TITLE
query sparql endpoint with apikey 

### ISSUE THREAD

**Issue by zhiboz** [paulovn/sparql-kernel#18]
thanks for a great tool! Is it feasible to query a sparql endpoint requiring an apikey?

**Comment by paulovn** [comment]
That depends on the mechanism. If the way the API key is specified is via a query parameter (i.e. the endpoint URL to use is something like `http://server.com/sparql&api_key=346e3f21`) then it would be easy. Just adding the capacity to include extra parameters in the endpoint URL would do the trick.

Do you know a (public) SPARQL endpoint that requires an api key, so that this can be tested?

**Comment by paulovn** [comment]
Version 1,1.0 contains a `%qparam` magic that can be used to add arbitrary parameters to the query string
