### ISSUE TITLE
Unexpected response format with local RDF4J repository

### ISSUE THREAD

**Issue by AlasdairGray** [paulovn/sparql-kernel#23]
When running any type of query (```CONSTRUCT``` or ```SELECT```) over a locally hosted RDF4J repository I'm getting the following error

`Error: Unexpected response format: application/sparql-results+xml`

The same queries run when I pose them over the RDF4J workbench endpoint. The notebook performs as expected when running queries over the DBpedia endpoint. 

I can see the query request reaching the endpoint by the RDF4J logs and it is running correctly.

How do I get queries running over my own endpoint to respond correctly for the SPARQL kernel?

**Comment by paulovn** [comment]
Hi. The errror message says that the kernel got a response in a MIME format that it cannot process, namely  `application/sparql-results+xml`. Which it's true, it cannot process it: as it is now, the code can only parse SPARQL results in JSON format (`application/sparql-results+json`). So, the default choice when sending a `SELECT` clause is to request results in JSON.

In your case it is not returning JSON, but XML. I can think of two reasons:
- Your RDF4J system does not understand the request (I'm relying the request to [`SparqlWrapper`](https://rdflib.github.io/sparqlwrapper/) and it might be that the option/header/whatever that `SparqlWrapper` uses in the request is not understood by RDF4J)
- RDF4J cannot generate results in JSON format

The first cause could be solved if there is a way to indicate the desired format to RDF4J that we can pass to `SparkqlWrapper`; the second is tougher, because it would be needed to modify the code to parse XML in addition to JSON (not a huge undertaking, but not trivial). I know nothing about RDF4J, so I'm not sure in which case we are.

Can you try to generate N3, to see if that is understood? Just add the magic

      %format n3

at the top of the cell.

**Comment by AlasdairGray** [comment]
I've been playing about with SPARQL Wrapper directly, running queries over my RDF4J (formally sesame) repository. It seems that when you use the GET method with RDF4J it can only return ```sparql-results+xml```. RDF4J can return JSON with POST but when I run that from SPARQL Wrapper it keeps returning a 500 error.

**Comment by paulovn** [comment]
With #24 I have added the capability to process responses also in XML format, so now it should work.

It's in version 1.1.0
